wikimedia/wikipedia-kaios

- index.html
- package-lock.json
- package.json
- src/index.js
- style/layout.less
- style/style.less
- webpack.config.js
Since we already use `webpack` as our Module Loader, it's a good practice to integrate with `loader` or `plugin`, therefore, add `less-loader` and related loader in webpack config file.
**Next step :**
Seperate `npm run build` `npm run start` to run either `development` or `production`, and choose when to minify the css file.
- https://webpack.js.org/loaders/less-loader/
> Integrate less-loader with Webpack

- src/api/wiki.js
- src/components/Article.js
- src/components/Pager.js
- src/hooks/useScroll.js
**Before :** Render lead section and all remaining section
**After :** Render lead as the first page, then render the next section with toclevel 1 when continue scrolling
This change updates the **render section by section** when user scroll to the last page.
When a user scrolls up when at the top of the section, will render the previous section's first page, the behavior is not very clear now, therefore we use this solution until we know it.
> Render the content section by section

- i18n/en.json
More consistent with other apps, and that's also what
the message documentation says.
Feel free to close it if it is supposed to say "Language setting".
> Change "Language setting" to "Language settings"

- src/api/getRandomArticleTitle.js
- src/api/search.js
- src/utils/index.js
- src/utils/mwApi.js
`URLSearchParams` doesn't appear to be working correctly in FF48. This change at least encapsulates the MW url building in one place.
> Encapsulate MW API URL in utils

- i18n/en.json
Splitting it to two sentences for better readability.
It has already been translated as two sentences with a full stop
to several languages, and it should have a full stop
in English as well.
> Remove comma splice from language-setting-message

- src/components/ListView.js
- style/listview.less
Currently, the image is being stretched due to the fixed size, the change centers image, similar to the mobile web search page.
| Before  | After |
| ------------- | ------------- |
| <img width="181" alt="Capture1" src="https://user-images.githubusercontent.com/2560096/71748233-30e9ce80-2e72-11ea-9761-d4b96248e07e.PNG">| <img width="179" alt="Capture2" src="https://user-images.githubusercontent.com/2560096/71748234-30e9ce80-2e72-11ea-8398-8da805a2f37e.PNG">|
> Set search image as background image

- src/components/ArticleMenu.js
- src/utils/articleHistory.js
- src/utils/index.js
1. Return `articleHistory` namespace instead object
1. add prev description in menu, https://phabricator.wikimedia.org/T241423#5773415
> Previous Article adjustment

- src/api/getArticle.js
- src/components/Article.js
- src/components/QuickFacts.js
- style/quickfacts.less
- style/variables.less
This is by no mean the end of quick facts. This commit
is just to restore the scrolling so that other people
can try it in the app.
> Fix quickfacts page scrolling

- cypress/integration/article-view-spec.js
- src/api/getArticle.js
- src/components/Article.js
- src/components/ArticleMenu.js
- src/components/QuickFacts.js
- src/components/Routes.js
- style/quickfacts.less
* Constrain the width for most cases
* Move to a popup instead of a route
* Add article menu entry
* Allow changing text size
https://phabricator.wikimedia.org/T234619
Known issue: Opening and closing a preview from the Quick Facts popup, leads you back to the article, not the quick facts. This is because we don't yet support multiple popups on top of one another. This will be addressed in a subsequent PR.
> Quick Facts

- style/menu.less
Fix weird error bottom in menu listview, when the menu list item is larger, then we will get
This css change fixed.
> Fix bottom style in menu

- cypress.json
- src/components/App.js
- src/components/ArticlePreview.js
- src/components/PopupContainer.js
- src/components/QuickFacts.js
- src/hooks/useArticleLinksNavigation.js
- src/hooks/usePopup.js
- style/popup.less
This is useful for situation where a popup brings another popup and closing the second one should return to the first one. For instance, showing article previews on top of quick facts.
> Support multiple popups

- src/api/search.js
It is possible to search for pages that are not articles
by using a namespce preffix in the search terms.
For instance: Help:Style, User_talk:SomeUserName,
or even Special:AbuseFilter
None of those results are relevant for this application.
This commit blocks those by replacing all colons with spaces.
It is possible for an article title to contain a colon but
very few do. And those who do generally have a redirect
from a similar title without it. I've included the "redirects"
API option to resolve redirects and mitigate the impact of
ommiting the colon.
> Block namespace search

- src/utils/languages.js
Test wiki is a site (for testing) in the production cluster but not a language.
> Remove "test wiki" from the language list

- src/components/Article.js
After the initial rendering of the article header page,
The .card component is added a margin-top to make sure
the .intro component fits perfectly at the bottom of
the page.
On text resize (make larger, 6), the .intro component
overflows to the next page and its height is reported
as bigger than it actually is. This causes the algorithm
to push the intro all the way up.
This commit resets the .card margin-top to 0 to make sure
the .intro is entirely visible.
> Header page positioning when text resizes

- cypress/integration/article-view-spec.js
- src/components/Article.js
- src/components/ArticleMenu.js
- src/components/Gallery.js
- style/article.less
- style/gallery.less
- style/mixin.less
- style/style.less
> Add Clamp to the description in gallery & Add Gallery item in Menu

- src/components/Gallery.js
Phabricator Link : https://phabricator.wikimedia.org/T236302#5879391
Currently, it does cycle the gallery item
do not repeat when reaches the end of last gallery item
> Gallery doesn't repeat when it reaches the end

- src/components/Article.js
Phabricator Link : -
Selecting the section doesn't work in the article
This is the bug fixed of https://github.com/wikimedia/wikipedia-kaios/pull/127, as we change to `anchor` instead of using the section `title`
> :bug: Use anchor instead title for sub page

- i18n/en.json
Phabricator Link : https://phabricator.wikimedia.org/T243413
There is ALL CAPS language key in en.json that is not recommended.
Follow the same pattern as other language keys
This key is being used in Article Footer as the title keyword.
> Change All Caps language key

- style/article.less
Phabricator Link : -
in some articles, it shows the skip top and bottom button on the view, see note screenshot
article `2019` http://localhost:8080/#/article/en/2019
hide
> Hide skip top and bottom button in article view

- cypress/integration/special-cases.js
- src/api/getArticleMedia.js
- src/components/Gallery.js
Phabricator Link : https://phabricator.wikimedia.org/T245966
The Gallery only works well in language `en` and sometimes doesn't show image in some items
1. capture the filename in `normalized` form
1. thumbnail can be missing in api, use `srcset` as the substitution
1. in case the image is not found in the gallery, show the first item to prevent script error
Please test well in different language, @jpita thanks for finding the bug here.
> {T245966} Adjust extra key to allow gallery in different languages

- README.md
- pull_request_template.md
Phabricator Link: https://phabricator.wikimedia.org/T245564
Here's a starting point for the development guide, adding to the README:
* Installation requirements
* Instructions to run app on browser and device
* Instructions to keep app updated
* Wikipedia logo at the end
You can [view what it would look like here](https://github.com/wikimedia/wikipedia-kaios/blob/T245564-README-update/README.md).  What do you think? Too much info? Anything we're missing? 
As hinted in the Phabricator task, we don't have to merge this right away if we want to wait until first version is more ready.
> T245564 readme update

- cypress/integration/article-view-spec.js
- src/api/getLanglinks.js
- src/components/RadioListView.js
- src/hooks/useSearchArticleLanguage.js
Phabricator Link : https://phabricator.wikimedia.org/T245712
As described in the [Phabricator ticket](https://phabricator.wikimedia.org/T245712), what's desired is that languages are searched with the native name ("english") instead of the localized name ("inglês")
Switching `llprop` field from `langname` to `autonym` in `getLanglinks` api
https://www.mediawiki.org/wiki/API:Langlinks
> Request native language name in getLanglinks

- index.html
- style/article.less
- style/articlelanguage.less
- style/confirmdialog.less
- style/error.less
- style/footer.less
- style/gallery.less
- style/language.less
- style/listview.less
- style/menu.less
- style/offline.less
- style/onboarding.less
- style/preview.less
- style/radiolistview.less
- style/search.less
- style/settings.less
- style/softkey.less
- style/textsize.less
- style/toc.less
- style/variables.less
Phabricator Link: https://phabricator.wikimedia.org/T245746
Currently, the app download the font family "Lato" from the google apis, and it against WMF user privacy policy
Upon checking on the default font styling in several devices, the font works well without assigning any font family, therefore the decision is to use the default font in each device.
If there is a source pass the policy, that's also not a bad idea to use.
> Remove font family and variable

- cypress/integration/article-view-spec.js
- src/api/getRandomArticleTitle.js
- src/api/search.js
- src/hooks/useSearch.js
- src/utils/cachedFetch.js
Phabricator Link: https://phabricator.wikimedia.org/T244021
1. Typing in search bar trigger unnecessary fetch event when there is a new search term
1. Press random article multiple times has console error 
1. There isn't abort/cancel event in `cachedFetch`
Implement `xhr.abort` in `cachedFetch`
currently, the random article uses `cachedFetch` with an extra key to make it non-cacheable fetch event,  we can make the fetch event more general to achieve cacheable and non-cacheable event but it requires more depth consideration of how we work with our cache mechanism and ajax (get) event.
Please test the app carefully with this update
> Abortable XMLHttpRequest

- package.json
Phabricator Link: https://phabricator.wikimedia.org/T247381
When using the deploy task, one can forget to rebuild the app and push outdated code to the device. It leads to confusion and waste of time.
Bundle the build task inside the deploy task.
> deploy task builds first

- src/utils/cachedFetch.js
Phabricator Link: https://phabricator.wikimedia.org/T244547
The user-agent has to contain an app identifier in order to count requests to the page content service as page views.
Add WikipediaApp/<version> at the beginning of the user agent for all API calls.
> Add app indicator to user-agent

- cypress/integration/settings-spec.js
- src/components/Settings.js
Currently we are unable to ask user to rate the app
Hide it and will release this soon
> Remove Rate the app from the settings

- src/hooks/useTracking.js
Phabricator Link: https://phabricator.wikimedia.org/T242358
The InukaPageView schema was updated to accept app_version but the revision was not updated in the code.
Use up to date schema revision.
Also remove referring_domain implementation that doesn't really work. We'll have to decide what we want to do with it but in the meantime it will not create schema validation errors.
> Update schema version and remove referring_domain implementation

- webpack.config.js
Webpack bundle size hints are not relevant here since all files are loaded locally on the device. 
Disable bundle size hints.
> Disable webpack bundle size hints

- scripts/manifest.js
- scripts/zip.sh
Phabricator Link: https://phabricator.wikimedia.org/T240886
After testing the app bundle on the KaiStore portal, I found that the manifest needs to be real JSON (duh) and the zip file needs to contain all files at the root.
* Format manifest correctly
* Add all files at the root of the zip
> Fix manifest formatting and zip structure

- src/utils/cachedFetch.js
- style/error.less
Since moving from `fetch` to `XMLHttpRequest`, error handling has been partly broken since most error cases call the load callback instead of the error callback.
Check the `status` and reject if it's not within [200-400[.
Also set the error component background to white.
> Fixed xhr error handling and error component background

- src/components/Search.js
Phabricator Link: https://phabricator.wikimedia.org/T245156
Remove random article feature from `Search` home screen
Removing from `Search` but leaving `getRandomArticleTitle` api as is given that [we will use it eventually](https://phabricator.wikimedia.org/T248124)
> T245156: Remove random article feature from left softkey

- .circleci/config.yml
- cypress.json
- cypress/integration/settings-spec.js
- cypress/page-objects/about-wikipedia-page.js
- i18n/en.json
- i18n/qqq.json
- package-lock.json
- package.json
- src/components/AboutWikipedia.js
- src/components/Routes.js
- src/components/Settings.js
- src/components/index.js
- style/aboutwikipedia.less
- style/style.less
Phabricator Link: https://phabricator.wikimedia.org/T236318
Reminder that it copies all the image and text from Onboarding page due to the similar content but different UI
Several things can be refactored but can wait
1. Header for the page can be generalized so we can reuse it in component and css
1. Let About App and About Wikipedia open as an popup, so user have the previous settings item selected when Close the about page
1. Reuse the same component for Onboarding and About Wikipedia?
| 1 | 2 | 3 |
| -- | -- | -- |
| ![1](https://user-images.githubusercontent.com/2560096/77183266-5f209700-6ace-11ea-90ab-7d763674a1fc.png) | ![2](https://user-images.githubusercontent.com/2560096/77183260-5def6a00-6ace-11ea-8de5-d087d9a18fda.png) | …
> T236318 Add About Wikipedia Page

- cypress/integration/article-view-spec.js
- cypress/integration/special-cases.js
- src/api/getArticleMedia.js
- src/hooks/useArticleLinksNavigation.js
a quick fix for media -> media-list
> Fix media list api

- src/hooks/useTracking.js
Phabricator Link: https://phabricator.wikimedia.org/T248757
When closing/refreshing the window, there are multiple beacons sent
remove pagehide event when one is being sent
This is part of the ticket {T248757}
> Fix multiple beacon sent when closing the window

- style/aboutapp.less
- style/aboutwikipedia.less
- style/onboarding.less
- style/variables.less
Phabricator Link: https://phabricator.wikimedia.org/T248286
'About the app' and 'About Wikipedia' pages are not rendering correctly in Jio2 devices.
Minor CSS adjustments 
~To be tested on Jio2 device by someone who has one, I have requested this on the Phabricator thread. Let's not merge until it's confirmed it looks good on device~
Tested by Sudhanshu on Jio2 device now
> T248286: Jio2 'About the app' and 'About Wikipedia' layout fix

- scripts/manifest.js
Phabricator Link: https://phabricator.wikimedia.org/T248675
KaiOS has a limited set of supported language. For displaying basic app information in the store, it needs the exact language codes it knows about. For instance, it supports both `fr-CA` and `fr-FR` and needs to see those codes exactly in the manifest. It won't pick up translations simply for `fr`.
Generate the manifest locales from the lists of supported locales for KaiOS and Jio and map to the i18n files as needed.
> App manifest: use only supported locales

- cypress/integration/article-view-spec.js
- src/components/Softkey.js
- src/utils/articleTextSize.js
Phabricator Link: https://phabricator.wikimedia.org/T248285
Because of the different keyboard in Jio2 devices (QWERTY), changing text size with 4, 5 and 6 is not intuitive.
Adding the following handlers for three letters to also have the same respective behavior:
* 's' to decrease size like 4
* 'd' to set default like 5
* 'f' to increase size like 6
I was able to test on browser and banana phone only. On browser, both s/d/f letter and 4/5/6 numbers are working, on banana phone the numbers work as usual and the letters don't (as expected). 
We need to test this on Jio2 device now.
Note that handlers are case sensitive. At the moment I don't know if pressing said letters on Jio2 keyboard will give you lowercase or uppercase, I'm assuming lowercase and left it as such in the code. If it's …
> T248285: allow letter 's', 'd' and 'f' to change text size in Jio2 device

- src/components/AboutApp.js
- src/components/AboutWikipedia.js
- src/components/Routes.js
- src/components/Settings.js
- src/reducers/SoftkeyReducer.js
Phabricator Link: https://phabricator.wikimedia.org/T248381
When you close the `AboutApp` and `AboutWikipedia` screens from `Settings` menu, the navigation position is not being kept
Render both `AboutApp` and `AboutWikipedia` screens as popups (instead of having a specific route for it)
> T248381: about pages

- src/api/getArticleMediaInfo.js
Phabricator Link: https://phabricator.wikimedia.org/T249468
Selecting "more info" about an image opens the desktop version of wikipedia or common and it doesn't seem to correctly detect KaiOS as mobile.
Force the mobile domain on those URLs.
> Link to mobile site for media

- src/utils/cachedFetch.js
Phabricator Link: https://phabricator.wikimedia.org/T249216
KaiOS app API calls appear to have no referer and that throws off the analysis.
Force a dummy referer so it's clear that the page views are internally referred (from the app, to the app)
> Set referer

- src/index.js
- src/utils/languages.js
Phabricator Link: https://phabricator.wikimedia.org/T249710
When user changes the device language, the app language doesn't change
Having two language storage for device and app language, always check whether the device language has changed before rendering the app
_code looks ugly ☹️ , do you have any idea?_
> T249710 Allow app language to always match device language

- src/components/ArticleLanguage.js
- src/components/ArticleMenu.js
- src/components/ArticleToc.js
- src/components/Language.js
- src/components/RadioListView.js
- src/components/Search.js
- src/components/Settings.js
- src/hooks/useNavigation.js
Phabricator Link: https://phabricator.wikimedia.org/T250253
When we changed the article menu so that popups stack, in order to get the desired back key behavior when working on [backspace key feature](https://github.com/wikimedia/wikipedia-kaios/pull/197/files), a bug was introduced because `useNavigation` hook was not prepared to handle a specific case such as `ArticleLanguage` stacked on top of `ArticleMenu`. What was happening is that on every `getAllElements()` call, it was actually getting all elements from both the first and second popup. This was messing up navigation altogether. 
At first I was trying to let it grab all elements from both popups and then slicing the array to handle the corresponding elements, but this approach wasn't really working correctly (branch …
> T250253: update useNavigation to support stacked popups

- package-lock.json
- package.json
- src/index.js
Phabricator Link: https://phabricator.wikimedia.org/T251255
You don't get this error on a modern browser, in the lower version of firefox < 58, and in KaiOS devices, the application throws error when calling Intl.PluralRules
Polyfill solution for Intl.PluralRules
> Add Intl.PluralRules polyfill

- src/utils/languages.js
Phabricator Link: https://phabricator.wikimedia.org/T251791
For the Goan Konkani language, Jio uses the kok-IN code but Wikipedia uses the gom code.
Map kok-IN to gom internally.
> Map kok-IN to gom (Goan Konkani Wikipedia)

- src/components/Article.js
- src/components/QuickFacts.js
Phabricator Link: https://phabricator.wikimedia.org/T252387
In some articles, contain reference markup but missing the reference object
do not open the reference preview popup when there isn't ref object found in the code
> guard reference before showing the popup

- src/api/getArticle.js
Phabricator Link: https://phabricator.wikimedia.org/T248079
Some images have a relative path that doesn't work in the app.
Make those image path absolute.
> Convert extension image src to absolute

- .stylelintrc.json
- style/article.less
Phabricator Link: https://phabricator.wikimedia.org/T249105
Some images didn't get the proper image treatment since it was applied only to figure.
Apply the image treatment to figure-inline as well.
> Apply image style to figure-inline

- cypress/integration/special-cases.js
- cypress/page-objects/article-page.js
- src/components/Gallery.js
- style/article.less
- style/gallery.less
Phabricator Link: https://phabricator.wikimedia.org/T247260
Some images render on top of each other or on top of article text.
Rename `.gallery` to `.gallery-view` so it doesn't conflict with the `.gallery` class used in articles. Also adjust margin and position.
> Fix image gallery rendering

- src/utils/languages.js
Phabricator Link: https://phabricator.wikimedia.org/T253158
Blacklisted language can be used when the phone is set to it but it breaks the application.
When the device is using a blacklisted language, fallback to english.
> Apply language blacklist even if the phone is set to use it

- src/api/getRandomArticleTitle.js
- src/api/search.js
- src/hooks/useArticle.js
- src/hooks/useArticleMediaInfo.js
- src/hooks/useArticleSummary.js
- src/hooks/useSearch.js
- src/hooks/useSearchArticleLanguage.js
- src/utils/cachedFetch.js
Phabricator https://phabricator.wikimedia.org/T244021
Components issue network requests. It is possible for those to resolve after the component has been unmounted. In this case, calling setState generates a runtime error and potentially a memory leak.
Make `cachedFetch` return a promise and an abort function for components to return in their `useEffect`.
> Let components abort pending requests

- src/components/Gallery.js
- style/gallery.less
Phabricator Link: https://phabricator.wikimedia.org/T250642
We had decided to temporarily remove the black background in the gallery as a consequence of [another gallery-related task](https://phabricator.wikimedia.org/T248443). The goal here is to bring the black background back and have the gallery display it correctly for both landscape and portrait images on device.
After many deploys trying out a number of ideas, I was finally able to get the device to render images properly with the use of `onImageLoad` only. The solution consists of looking at the dimensions of each new image in the gallery and deciding based on its width and height whether said image is a portrait or landscape. With this information, we can then set CSS appropriately for each case. Note that:
- You will notice …
> T250642: bring back the gallery black background

- .circleci/config.yml
- cypress/integration/article-view-spec.js
- package.json
- src/utils/cachedFetch.js
- src/utils/featureFlags.js
- webpack.config.js
Our environment on the phone is firefox browser
Update the cypress configuration and our app feature flag to be able to run on firefox
_I believe our app won't be able to work correctly when KaiOS updates the gecko engine to the latest, for example, if you run our app on chrome, the article page navigation doesn't work well due to the reason we are now developing it for the older firefox. The good thing is we may not need the `isProd` utils for setting request header._
> Update cypress to run on firefox

- cypress/integration/article-view-spec.js
- src/hooks/useArticleLinksNavigation.js
Phabricator Link: https://phabricator.wikimedia.org/T248171
Device unable to have "goto" section feature
due to the different pathname, add additional logic for device
browser works correctly now, but not device, therefore this change is for device
> T248171: add additional logic for device when checking links action

- src/utils/languages.js
Phabricator Link: https://phabricator.wikimedia.org/T247255
Hindi is missing from the Jio prioritized language list.
Add it
> Adding Hindi to the Jio language list

- src/components/Article.js
- src/components/QuickFacts.js
- src/hooks/useArticleLinksNavigation.js
Phabricator Link: https://phabricator.wikimedia.org/T253018
If an image is not supposed to be shown in the gallery, it shouldn't be selectable. Otherwise it leads to a buggy behavior where a user can click on an image (from article) and then see a different image in the gallery view. 
Check whether the image in the article section is part of the gallery images before adding it as a `visibleLink`. This includes images shown in `QuickFacts`
> T253018: only gallery images should be selectable

- src/components/Search.js
Phabricator Link: https://phabricator.wikimedia.org/T254307
Using the backspace key on Search performs a soft/partial close (app stays running on the background) as opposed to a hard/full close (kills the app). With the app running on the background after a soft close, the app updates won't be picked up by device.
According to the solution suggested in Phabricator as well as what I can find online [1], `window.close()` performs the hard close that we need to kill the app. Main question then is how we can actually test that to corroborate. 
The main evidence I was able to find to confirm the hard close is the behavior seen via the WebIDE, specifically the dev tools panel available with remote runtime:
* without `window.close` (so what's currently on `master`), pressing backspace closes the …
> T254307: add onKeyBackspace handler to Search

- src/components/Consent.js
Phabricator Link: https://phabricator.wikimedia.org/T255397
When we accept the terms (on first app boot after install) a call is sent to the logs. When offline, a user can still use some basic functionality on the app.
Show the offline panel UI and hide the CSK button
_higher priority review task_
> T255397 Offline status for consent page

- src/components/Feedback.js
Phabricator Link: https://phabricator.wikimedia.org/T236317
This is a follow up to #216, it was requested to update `Feedback` navigation to:
> Use up/down keys on D-PAD to switch control between the text box and fine print and use left/right keys to switch between links
I [shared my takeaways](https://phabricator.wikimedia.org/T236317#6230469) in the Phab ticket, it became evident to me that having both up/down and right/left arrow key handlers for a _single_ screen is basically not common/present anywhere else in the app, and therefore slightly against overall app consistency. If we want to go through with it though, to achieve the requested behavior then I'm proposing a `onKeyArrow*` for each of the four options and using `setNavigation` to select. Feels like some of the logic could be …
> T236317: add specific arrow keys handlers

- cypress/integration/article-view-spec.js
- cypress/integration/settings-spec.js
- cypress/support/commands.js
- package.json
- src/components/ArticleLanguage.js
- src/components/Language.js
Phabricator Link: https://phabricator.wikimedia.org/T254311
Language lists use radio buttons. To select a language, the user has to select the radio button first and then click the left softkey to go back.
Use buttons so that selecting a language applies it immediately. This is also how KaiOS does it.
Adding a npm task to run the browser tests with Chrome. Firefox doesn't work for me.
> Language lists use buttons

- style/listview.less
Recently, the search article language changes from RadioListView to ListView component, and the RTL Support for the component is missing in ListView
Adding the rtl language styling for the ListView
UI language RTL support will visit this again, especially dealing with the image listview. But for now this is just for the normal listview.
> Quickfix for the RTL in Listview component

- src/utils/languages.js
ha language was incorrectly classified as RTL
Remove it from the RTL list.
> ha language was incorrectly classified as RTL

- src/components/ArticleFooter.js
Phabricator Link: https://phabricator.wikimedia.org/T247444
The article footer is presented as part of the article content but it is using the UI language. When the UI and content languages are not the same, it creates a surprising experience.
Localize the footer using the article content language.
> Show article footer in content language

- src/components/Article.js
Phabricator Link: https://phabricator.wikimedia.org/T247443
Article actions are displayed as part of the article content, under the title on the first page. When the UI and content languages are different, this creates a surprising experience for the user. These actions are also available in the article menu, which remains in the UI language.
Show the action labels in the article content language.
> Localize article actions in content language

- src/utils/articleHistory.js
Phabricator Link: https://phabricator.wikimedia.org/T262602
Article history can become large and fill up local storage.
There's no reason to put it in local storage. Store in a regular variable and limit its size to 100.
> T262602 article history

- cypress/integration/article-view-spec.js
- cypress/integration/references-popup.js
- package-lock.json
- package.json
Phabricator Link: https://phabricator.wikimedia.org/T263109
banana-i18n was update from 1.2.1 to 1.3.1 (even though it was not needed) in #271 to fix npm audit warnings. That version turns out to error out on the reference dialog title message. Will follow up with banana-i18n separately. 
Downgrade banana-i18n from 1.3.1 to 1.2.1
> Fix reference preview by downgrading banana-i18n

- style/article.less
- style/links.less
Phabricator Link: https://phabricator.wikimedia.org/T260391
References have an outline around every single character. See task for screenshots.
bidi-isolate the whole reference link so it doesn't switch direction and has a single outline.
> Fix outline fragmentation by using border

- style/input.less
- style/style.less
Phabricator Link: https://phabricator.wikimedia.org/T260114
input mic icon overlap with the placeholder in RTL language
update the input css
**Tested on KaiOS NOKIA flip phone**; if you don't see any mic icon on your device, then this change doesn't affect it.
| LTR | RTL (1) | RTL (2) | RTL (3) |
| -- | -- | -- | -- |
| ![image](https://user-images.githubusercontent.com/2560096/93746762-f4bfef00-fbf5-11ea-88c3-486b3a2b7472.png) | ![image](https://user-images.githubusercontent.com/2560096/93746778-fb4e6680-fbf5-11ea-8412-25cdd4ffaaf8.png) | ![image](https://user-images.githubusercontent.com/2560096/93746799-01dcde00-fbf6-11ea-8a56-c9e039bbcef8.png) | ![image](https://user-images.githubusercontent.com/2560096/93746816-06a19200-fbf6-11ea-8346-17d8d5ff3595.png) |
> T260114 Configure input element mic icon

- src/hooks/useSearchLanguage.js
- src/utils/languages.js
Phabricator Link: https://phabricator.wikimedia.org/T262592
Our Kibana dashboard shows the following error info
```
message: v is undefined
---
stack trace:
getInitialLangList/<@app://kaios.wikipedia.org/dist/main.js:1:395829
getInitialLangList@app://kaios.wikipedia.org/dist/main.js:1:395809
useSearchLanguage/<@app://kaios.wikipedia.org/dist/main.js:1:395323
q@app://kaios.wikipedia.org/dist/main.js:1:283028
I.__c/</h.__h<@app://kaios.wikipedia.org/dist/main.js:1:285570
I.__c/<@app://kaios.wikipedia.org/dist/main.js:1:285531
I.__c@app://kaios.wikipedia.org/dist/main.js:1:285471
T@app://kaios.wikipedia.org/dist/main.js:1:267101
_/<@app://kaios.wikipedia.org/dist/main.js:1:262636
_@app://kaios.wikipedia.org/dist/main.js:1:262455
---
App version: 1.0.0.1231
```
As part of the initial …
> T262592: fix production error ('v/h is undefined')

- manifest.webapp
Phabricator Link: https://phabricator.wikimedia.org/T267262
For some versions of KaiOS, access to the internet via mobile plan or wiki needs to be requested explicitly in the manifest.
Specify `mobiledata` and `wifidata` permissions in the manifest.
> Specific data permission in the manifest

- images/arrow.svg
- src/components/Gallery.js
- style/gallery.less
Phabricator Link: https://phabricator.wikimedia.org/T267291
In gallery view, no arrow indicator to show more images
Add the arrow indicator svg within Gallery
| ![image](https://user-images.githubusercontent.com/2560096/100120840-b30f2700-2e78-11eb-9808-d5768303af80.png) | ![image](https://user-images.githubusercontent.com/2560096/100120863-ba363500-2e78-11eb-9402-a24bb2cf42b1.png) |
| --- | --- |
> T267291 Add visual indicator to show more images inside gallery

- i18n/en.json
- i18n/qqq.json
https://phabricator.wikimedia.org/T267560
During a recent KaiOS app usability study, the word "Sections" was not clear in its meaning or function.
Replace the word "Sections" with "Contents" in the quick links panel and the article menu
> T267560: Update language from 'Sections' to 'Contents'

- cypress/integration/special-cases.js
- src/components/ConfirmDialog.js
- src/components/Feedback.js
- src/hooks/usePopup.js
Phabricator Link: https://phabricator.wikimedia.org/T269158
The confirm dialog close event has `close` `closeAll` option, but it doesn't allow us to choose which one
Make the confirm dialog utils/component more general
touch to the confirm dialog and popup related code, including hook
> T269158 Confirm dialog - Close event

- i18n/en.json
- style/confirmdialog.less
Phabricator Link: https://phabricator.wikimedia.org/T262249
Follow up issue
the confirm dialog box update 3 places and confirmed by design
| ![image](https://user-images.githubusercontent.com/2560096/101754759-62ccd180-3ad4-11eb-83b9-d1efd2f01d88.png) | ![image](https://user-images.githubusercontent.com/2560096/101754786-682a1c00-3ad4-11eb-8e76-ef9eabb0489e.png) | ![image](https://user-images.githubusercontent.com/2560096/101754804-6ceed000-3ad4-11eb-9db5-4b6cb4766351.png) |
| --- | --- | --- |
> T262249 Follow up : Implement a confirmation dialogue when closing the app

- src/hooks/useI18n.js
Phabricator Link: https://phabricator.wikimedia.org/T269856
Some French messages have unsupported GENDER syntax. It breaks the app.
The messages have been fixed in TWN but they should not have broken the app. This PR adds try/catch and a fallback chain to make sure it doesn't happen again.
> Handle message parsing errors

- cypress/integration/search-spec.js
- src/api/search.js
- src/components/ListView.js
Phabricator Link: https://phabricator.wikimedia.org/T268751
During search, prefix search always return empty result
use fulltext search instead
well, I can't tell wether the result is better, and <s>can't find the correct prop to return thumbnail</s> ios related code https://github.com/wikimedia/wikipedia-ios/blob/1bc0cea71e2556b60e8b30701e162318f737ffbb/Wikipedia/Code/WMFSearchFetcher.m#L77
> T268751 Use Fulltext search in Search screen

- scripts/manifest.js
The JioStore has updated their version checking algorithm so that 1.2.0.0 > 1.0.0.1231 so we don't need a long (.1000) forth digit anymore.
Use a single non-significant 0 as version padding.
> Shorten Jio store version padding

- src/hooks/useArticleLinksNavigation.js
https://phabricator.wikimedia.org/T271359
When an [article has no images](http://localhost:8080/#/article/fr/Veto), the gallery array is provided as an empty array (as opposed to `undefined`). The one case I can spot where `galleryItems` is provided to `useArticleLinksNavigation` as `undefined` is when invoked via `ReferencePreview`. I haven't found yet a specific example of a reference that replicates the issue, it would have to be a reference that contains a `figure` or `figure-inline` tag (is that even possible?). Also, the links navigation does not break for either `ReferencePreview` or `Article` as far as I can tell
> T271359: add undefined guard to isImageInGallery

- style/article.less
Phabricator Link: https://phabricator.wikimedia.org/T272484
page
`es/Elecciones_presidenciales_de_Estados_Unidos_de_2020/Referencias`
> T272484 style for listaref class

- src/components/Search.js
- src/hooks/useSearch.js
Phabricator Link: https://phabricator.wikimedia.org/T272276
Searching for empty string returns no results
Trim the search query and only search if it is not empty
> Trim search query to prevent searching for empty string

- src/utils/experiment.js
Phabricator Link: https://phabricator.wikimedia.org/T271904
We only want the control and trending groups for now.
Removed the topics group.
Renamed the storage key so this group assignment is specific to this experiment.
> Only 2 groups for now

- src/api/getExperimentArticles.js
- src/utils/experiment.js
Phabricator Link: https://phabricator.wikimedia.org/T271910
API and utils related to the topics feed are not needed anymore.
Remove the API and utils related to the topics feed.
> Remove unneeded topics feed API and utils

- src/components/Gallery.js
- style/gallery.less
The gallery left/right arrows are not visible in the simulator because they are set in CSS with an absolute path.
Change the arrows from div with background image to img with src and relative path so they are visible in the simulator.
> Show gallery arrows in simulator

- src/hooks/useSearch.js
Phabricator Link: https://phabricator.wikimedia.org/T272276
After typing a character, additional spaces trigger new search queries.
Trim the search terms so that equivalent search queries are returned from the cache.
> Trim the search terms

- .circleci/config.yml
Wouldn't it be nice to be able to test any branch in the simulator without downloading the code?
Deploy every branch to gh-pages
Example: https://wikimedia.github.io/wikipedia-kaios/sim-all-branches/sim.html
There is no automated way to clean up the old branch directories after they are deleted, I'll clean them up manually once in a while.
> Deploy the app and simulator for all branches

- src/hooks/useTracking.js
Phabricator -
We want to release a pre-experiment version of the app.
Don't include the `tests` key in the InukaPageView experiment just yet.
> Temporarily disable logging experiment group in InukaPageView

- scripts/zip.sh
When configuring the source-map for debugging in #307, I accidentally changed the bundling to have main.js at the root of the zip instead of in the dist folder. That breaks the bundle.
Put main.js back in the dist folder in the application bundle (zip).
> Put main.js back in the dist folder

- src/components/Search.js
https://phabricator.wikimedia.org/T271904
This is just a minor followup to #322, I ran into this little bug today.
If you expand the feed and click on some article, then go back to `Search`, you will land on the feed with that last index selected, as requested by design. No issues there. If you then hit backspace, and then go to `Settings`, and then hit backspace again: you land on the expanded feed again, when it should be collapsed instead.
We should also reset `lastFeedIndex` within `onKeyBackSpace` because that's a valid way to collapse the feed (besides `onKeyArrowUp`).
> T271904: minor followup 

- .eslintrc.js
- README.md
- cypress.json
- cypress/integration/search-spec.js
- cypress/integration/special-cases.js
- package.json
Add access to cypress dashboard
https://dashboard.cypress.io/projects/7izdto/runs
Super handy to trackdown flaky tests and to get an overview of our tests and metrics.
Also added a badge to the README that shows the test run status and numbers.
Also added test retries that hopefully makes our builds more reliable in case we have a flaky test.
> Add cypress dashboard

- src/api/getExperimentConfig.js
We've seen the fetching of the experiment config fail from time to time in CI with "page.revisions is undefined". Wondering whaat's up with that.
Log a warning with the content of the API response when this happens.
I hope this is temporary.
> Harden experiment config

- sim.html
Make the sim screen the same size as a known device (banana phone).
> Device screen height is 290px (320px - 30px (top bar))

- src/utils/sendErrorLog.js
Without the `hasty` param the server will validate the schema before returning. It's great for development for we have a change to notice if we're sending invalid events but for production it's better to make it hasty.
Add the `hasty` param in production
Sim Link: https://wikimedia.github.io/wikipedia-kaios/<BRANCH NAME>/sim.html
> Error logging: use ?hasty param in prod

- sim.html
iframe scrollbar annoying in Windows
hides the scrollbar used by iframe
Before / After
Sim Link: https://wikimedia.github.io/wikipedia-kaios/iframe-scrollbar-no/sim.html
> disable scrolling for simulator

- sim.html
Phabricator Link: https://phabricator.wikimedia.org/T277257#6934235
Object.entries is not available in Chrome 49
Use Object.keys
Sim Link: https://wikimedia.github.io/wikipedia-kaios/<BRANCH NAME>/sim.html
> Avoid Object.entries

- src/api/getTrendingArticles.js
- src/components/Feed.js
https://phabricator.wikimedia.org/T278133
The list of trending articles fetched from mediawiki may contain more than 5 items but the app should only use the first 5.
Sim Link: https://wikimedia.github.io/wikipedia-kaios/T278133-feed-max/sim.html
> T278133: Display only the first 5 items in feed list

- i18n/en.json
- i18n/qqq.json
- src/api/getTrendingArticles.js
- src/components/Feed.js
- style/feed.less
https://phabricator.wikimedia.org/T277497
How should the app react when the api returns falsy/empty data. A potential solution is an error state to render in the feed UI, instead of just an empty feed (which is the current behavior).
We also need to we need to log it in our client-side errors stream (`sendErrorLog`)
Sim Link: https://wikimedia.github.io/wikipedia-kaios/T277497-feed-error/sim.html
> T277497: Add basic error handling for trending articles feed

- src/components/Feed.js
- src/components/Search.js
https://phabricator.wikimedia.org/T271677
Huei found this bug: if user selects an article from trending feed and then hits `backspace` to return to the feed, the `lastIndex` item is not rendered as selected (and instead the first item is highlighted 🐛). This is because a `setNavigation(1)` from a second `useEffect` is overriding the navigation logic for when the user returns from article. This bug was introduced in #337. 
We can actually simplify the `useEffect` calls into one because they actually perform similar/complementary logic with `setNavigation`. The dependencies observed remain the same (`trendingArticles`, `loading`, `isExpanded`)
Sim Link: https://wikimedia.github.io/wikipedia-kaios/T271677-feed-loading-followup-lastIndex-bug/sim.html
> T271677: Remove setNavigation conflict

- scripts/stats.sh
- scripts/stats_header.sh
- scripts/stats_line.sh
Phabricator Link: https://phabricator.wikimedia.org/T283725
It was reported that the KaiOS app was using too much memory. The memory tab in Firefox dev tools can take memory snapshots at any given time but it cannot show live usage.
This script can be left running while the app is being used to generate a log of memory usage and other metrics.
Sim Link: N/A
> Script to capture memory usage, and other stats, in real time

- src/api/getLanglinks.js
- src/utils/languages.js
Phabricator Link: https://phabricator.wikimedia.org/T280274
The langlinks API returns the language code 'nb' for Norwegian (Bokmal) but Wikipedia uses 'no' as the subdomain. 
Convert the API response from 'nb' to 'no'
To test, I used `en/Earth`, then use the language button to switch to `no/Jorden`
Sim Link: https://wikimedia.github.io/wikipedia-kaios/no-nb/sim.html
> Convert lang code nb to no for Norwegian (Bokmal)

- scripts/stats_header.sh
- scripts/stats_line.sh
The stats script prints a bunch of columns and it hard to know which ones are relevant
Print only the USS and PSS columns so it's easier to troubleshoot memory usage.
Sim Link: Not relevant
> Print only the relevant memory stats

- src/components/Gallery.js
Phabricator Link: https://phabricator.wikimedia.org/T286725
Follow-up to #372 
The gallery/about feature doesn't have access to the media info and stays in loading state.
Add `mediaInfo` as a softkey dependency so that the handlers are updated when the media info becomes available.
Sim Link: https://wikimedia.github.io/wikipedia-kaios/mediaInfo/sim.html
> Fix Gallery/About

- cypress/integration/search-spec.js
- cypress/support/commands.js
- sim.html
- src/components/App.js
- src/components/Search.js
- src/components/Softkey.js
Phabricator Link: https://phabricator.wikimedia.org/project/view/4301/
EndCall / Backspace when user on input or search list, see phab ticket for more details
Sim Link: https://wikimedia.github.io/wikipedia-kaios/T311141-EndCall/sim.html
> Add EndCall key to Search.js and remove Global EndCall handler
