package-lock.json
package.json
webpack.config.js

all the dev server configuration can be done in webpack config file, listen to the file changes but doesn't support hot reloading (not sure whether needed, will revisit if needed)

Add webpack-dev-server to server localhost, and listen the changes

---

cypress/page-objects/search-page.js
src/components/ListView.js
src/components/Search.js
src/components/index.js
style/listview.less
style/search.less
style/style.less

> props : 
> { items : { title, titleHtml, description, imageUrl }, containerRef }

Abstract <ListView/> Component

---

src/components/Search.js
src/components/Settings.js
src/hooks/useNavigation.js

this pr includes the minor changes of onKeyCenter event in Search page.

Open Link in Setting page

---

src/api/wiki.js

imgNode gets the image `//<img url>`, so we need to modify it first before parsing the string

Fix the missing image link for the section image

---

src/api/getArticle.js
src/api/index.js
src/api/search.js
src/utils/cachedFetch.js
src/utils/index.js

utils cachedFetch method

---

src/api/getArticle.js
src/hooks/useArticlePagination.js

let me know if anyone found more issues on ToC

Fix ToC bug found

---

src/hooks/useArticlePagination.js

Calculate the scrollLeft position based on the element left position

---

src/api/getArticle.js

Otherwise we sometimes end up selecting a small icon and stretching it to 240px wide

Select section images that are not too small

---

src/components/Article.js
src/components/ArticleToc.js
src/components/QuickFacts.js
src/components/Search.js
src/components/Settings.js
src/utils/viewport.js
style/article.less
style/layout.less
style/preview.less
style/quickfacts.less
style/search.less
style/variables.less

I replace most of them using % so that it can fit _"most"_ of the device.
I also update some stylings as shown below 
_(highlight selected a text)_
_(highlight selected action button)_

Support Responsive Layout

---

cypress/support/commands.js
src/components/Article.js
src/components/ArticlePreview.js
src/components/ArticleToc.js
src/components/Language.js
src/components/QuickFacts.js

quick update of https://phabricator.wikimedia.org/T241044
so we can feel the consistency with the physical device keyboard ^^

the close key should always on right softkey

---

style/article.less

I don't know why I did that. It's not in the spec and it's ugly.

Don't justify article text

---

index.html

It would probably be better to include the font in the bundle but for now, this will allow us to bring the style closer to what it should be.

Fetch Lato font

---

src/components/Language.js
src/hooks/useSearchLanguage.js

Thanks @jpita for finding this Capital input error in Search Language Bar

Fix error when typing capital letter in search language bar

---

src/api/getArticle.js

quick adding, I remember someone who requests for this.

Add article title as the first section in toc

---

style/article.less

fixed for https://phabricator.wikimedia.org/T240790#5757404

quick styling update for gallerybox

---

src/api/getArticle.js

https://phabricator.wikimedia.org/T242192

Don't error out on articles that don't have an intro paragraph

---

i18n/en.json
src/components/TextSize.js
src/utils/articleTextSize.js

Phab. : https://phabricator.wikimedia.org/T234622

Textsize adjust

---

i18n/en.json
i18n/qqq.json
src/components/ArticleLanguage.js
src/components/Language.js
src/components/ListView.js
src/components/RadioListView.js
src/components/Search.js
style/listview.less
style/radiolistview.less

for https://phabricator.wikimedia.org/T242350

Empty State for Search and Article Language Page

---

cypress/integration/search-spec.js
cypress/page-objects/search-page.js

I test it all the time to prevent bad thing happens, so I'm adding one test here

Add empty result found test case in search page

---

src/components/Onboarding.js
src/hooks/useSoftkey.js
src/reducers/SoftkeyReducer.js

_Internal change how we pass the config to softkey component_
1. allow `replace` the softkey type, default to `set`
_Edit_: Turns out, get function is not needed

Add more options to useSoftkey configuration

---

src/api/getArticleSummary.js
src/components/ArticlePreview.js

to avoid redirection, we get the actual title 
see https://phabricator.wikimedia.org/T242350#5816578

Read canonical title when it's available in article preview

---

src/api/getRandomArticleTitle.js

It tries to provide better results than the MW API
See https://www.mediawiki.org/wiki/Wikimedia_Apps/Team/RESTBase_services_for_apps#.../page/random/{format}

Use the random PCS endpoint

---

src/components/Article.js
src/components/ArticleMenu.js
src/components/Language.js
src/components/Settings.js
src/utils/confirm.js

Remove popup position auto which is by default

---

src/components/RadioListView.js
style/radiolistview.less

styling update
| Before | After |
| --- | --- |
| <img width="180" alt="Capture-before" src="https://user-images.githubusercontent.com/2560096/73336825-393cfa00-42b6-11ea-8728-173615ce41cb.PNG"> | <img width="179" alt="Capture" src="https://user-images.githubusercontent.com/2560096/73336843-41953500-42b6-11ea-9172-9129200fefd4.PNG">|

Update Radio List View radio style

---

src/api/getArticleMedia.js
src/components/Gallery.js
style/gallery.less

update header to use caption, about description to use description
&
adjust gallery style when there hasn't header (caption)

Update gallery header to use caption

---

style/gallery.less

see the comment https://phabricator.wikimedia.org/T236302#5845706

Add background color for gallery image

---

i18n/en.json

https://phabricator.wikimedia.org/T236262#5855658

Add brand in search placeholder to increase awareness

---

cypress/integration/article-view-spec.js
cypress/page-objects/article-page.js
cypress/page-objects/quick-facts-page.js

add test to check that the quick facts page is opening from:
* the main article page
* the article menu

add test to check that the quick facts page

---

cypress/integration/article-view-spec.js
cypress/page-objects/article-menu-page.js

add test to check link from quick facts

add test to check link from quick facts

---

cypress/integration/article-view-spec.js

Phabricator Link : https://phabricator.wikimedia.org/project/view/4301/
_Describe the statement of this pr_
_Describe the technical solution and attach the screenshot if needed_

add check for flipping images on the gallery view

---

src/components/Article.js
src/components/ArticleLanguage.js
src/components/ArticleMenu.js
src/components/ArticlePreview.js
src/components/ArticleToc.js
src/components/ConfirmDialog.js
src/components/Error.js
src/components/Gallery.js
src/components/Language.js
src/components/Loading.js
src/components/QuickFacts.js
src/components/ReferencePreview.js
src/components/Search.js
src/components/Settings.js
src/components/TextSize.js

Phabricator Link : https://phabricator.wikimedia.org/T245438
Current app has the opposite behaviour of left and right key action
Follows the rule
```
LSK: Close actions
RSK: Menu and settings options
```

Interchange LSK and RSK actions

---

src/hooks/useSearch.js
style/article.less
style/layout.less
style/loading.less
style/onboarding.less

Phabricator Link : -
The browser/app are currently showing either white blank w (w/o) empty list result message when booting the app. (assume you have onboard the app before and then exit the app)

Fix White Blink when booting app

---

src/utils/languages.js

Phabricator Link : -
There are some missing language in our language list 
Maithili : मैथिली
Bodo : बड़ो
Goan Konkani (Devanagari script) : गोवा कोंकणी

Add language for Maithili, Bodo, Goan Konkani

---

style/articlelanguage.less
style/language.less
style/search.less

There is a gap
| Before | After |
| --- | --- |
| ![Screen Shot 2020-03-05 at 14 53 18](https://user-images.githubusercontent.com/2560096/75988132-6aca6600-5ef1-11ea-8fff-7ee11106d42c.png)| ![Screen Shot 2020-03-05 at 14 53 39](https://user-images.githubusercontent.com/2560096/75988150-70c04700-5ef1-11ea-8311-d294647f5c62.png)|

Fix the gap between the header and list

---

README.md

Small README update to account for https://github.com/wikimedia/wikipedia-kaios/pull/172

Update README: remove app build step

---

.circleci/config.yml
.gitignore
scripts/manifest.js
scripts/zip.sh

Phabricator Link: https://phabricator.wikimedia.org/T240886
This application needs to be bundled in a zip to be distributed to stores. Also, the manifest needs to be updated with application info in various languages.
`scripts/manifest.js` generates a new manifest with updated locales and version
`scripts/zip.sh` copies all needed files and folders to a temp dir and makes a zip file called app.zip
The script above is executed in CI and the resulting bundle is saved as an artifact in CircleCI.

T240886 app package

---

cypress/support/commands.js
package-lock.json
package.json
src/components/AboutApp.js
src/components/AboutWikipedia.js
src/components/Article.js
src/components/ArticleFooter.js
src/components/ArticleLanguage.js
src/components/ArticleMenu.js
src/components/ArticlePreview.js
src/components/ArticleToc.js
src/components/ConfirmDialog.js
src/components/Error.js
src/components/Gallery.js
src/components/Language.js
src/components/Loading.js
src/components/OfflineIndicator.js
src/components/Onboarding.js
src/components/QuickFacts.js
src/components/ReferencePreview.js
src/components/Search.js
src/components/Settings.js
src/components/Table.js
src/components/TextSize.js
src/hooks/useArticle.js
src/hooks/useArticleLinksNavigation.js
src/hooks/useI18n.js
src/index.js

Following the PR of https://github.com/wikimedia/wikipedia-kaios/pull/190
Phabricator Link: https://phabricator.wikimedia.org/T248354
banana doesn't allow us to grab another locale translation without changing the locale
Two interface usage of i18n : `i18n()` for UI lang, `i18n( lang )` for given lang translation
simplify `i18n.i18n()` to just `i18n()`
<s>Test spec completely fail, but in the meanwhile, this is ready to be reviewed</s>

T248354 update useI18n() interface

---

style/aboutapp.less
style/aboutwikipedia.less
style/onboarding.less
style/variables.less

Phabricator Link: https://phabricator.wikimedia.org/T248290
Onboarding pages are not rendering correctly in Jio2 devices.
Minor CSS adjustments
Tested by Sudhanshu on Jio2 device already.

T248290: Jio2 onboarding layout fix

---

src/components/ArticleLanguage.js
src/components/Language.js
src/hooks/useSearchArticleLanguage.js
src/hooks/useSearchLanguage.js

Phabricator Link: https://phabricator.wikimedia.org/T248287
Jio2 devices let users select a "predictive text" when typing a language, this adds an extra space at the end of input string
Trimming input in both `Language` and `ArticleLanguage`
Extra space is doesn't affect search in `Search` input, so leaving as is

T248287: trim user input when changing language

---

src/api/getLanglinks.js
src/utils/languages.js

Phabricator Link: https://phabricator.wikimedia.org/T249723
Some languages don't have font available on the devices so they show as tofu
Blacklist those languages for now.

Blacklist languages missing font on devices

---

src/api/getLanglinks.js
src/utils/languages.js

Phabricator Link: https://phabricator.wikimedia.org/T250220
RTL languages are not currently supported in the app
Disable them until we can support them so it doesn't look all broken.

T250220 rtl

---

src/components/Table.js

Add the missing backspace key in Table component
original pr : https://github.com/wikimedia/wikipedia-kaios/pull/197

Add backspace key to table component

---

package-lock.json
package.json

Phabricator Link: https://phabricator.wikimedia.org/project/view/4301/
stylelint-config upgrade
The stylelint-config version is upgraded and the app is tested to make sure it's working smoothly
Screenshot also attached ensuring the stability of the app.

stylelint-config upgrade

---

style/privacyterms.less
style/usageconsent.less

Phabricator Link: https://phabricator.wikimedia.org/T250219
Following up on https://github.com/wikimedia/wikipedia-kaios/pull/218 to adjust rendering in Jio2 devices
CSS tweaking
Let's definitely not forget to squash and merge this one

T250219: Instrumentation consent follow up

---

package.json

Update package.json bugs url link to Phab.

---

src/components/Search.js

Fix random api promise

---

.circleci/config.yml
.gitignore
scripts/zip.sh
src/hooks/useSearchLanguage.js
src/utils/featureFlags.js
src/utils/languages.js
webpack.config.js

Phabricator Link: https://phabricator.wikimedia.org/T247255
When the user goes to change the search/UI language, we show a short list of 10 somewhat arbitrary languages.
Allow for a special initial list of languages that is more relevant to Jio users in India. 
CI will now generate two application bundles (zip files). One for Jio and one for generic KaiOS.

T247255: Prioritized Languages

---

src/api/getArticleMediaList.js

on article `كليوباترا_الساته` in language `arz`, when api returns ` ` caption, bad UI looking
trim the caption
_Really edge case_
| Before | After |
| --- | --- |
| ![Screen Shot 2020-06-15 at 17 55 36](https://user-images.githubusercontent.com/2560096/84679737-f6f91a00-af31-11ea-98e4-7c31acc08433.png) | ![Screen Shot 2020-06-15 at 17 55 19](https://user-images.githubusercontent.com/2560096/84679738-f791b080-af31-11ea-9be3-81d085222962.png) |

Minor - Trim caption from media list api

---

src/components/Consent.js

Phabricator Link: https://phabricator.wikimedia.org/T255397
Show the offline panel and don't show the softkey when offline
clear the softkey
_we can have util or dispatch to clear all softkey, given that this is the only case, therefore these all the `isOnline` state check for each_

T255397 Consent page - Clear softkey when offline

---

scripts/manifest.js
src/components/AboutApp.js
src/utils/appVersion.js
webpack.config.js

I don't know which version of the app is published to the store.
Include the CircleCI build number as the 4th digit of the version.

Include the circleci build number in the app version

---

src/utils/consent.js

Sindhi is using the wrong script, comment out and let the fallback be used
bpy and brx were reversed

Fix agree consent messages

---

src/components/Feedback.js
src/components/Language.js
src/components/Search.js
style/feedback.less

Phabricator Link: https://phabricator.wikimedia.org/T236317
This PR is the continuation of #252, which was merged early accidentally. This includes better rendering of messages in Hindi and some refactoring.

T236317 feeback component follow up 2

---

src/components/Consent.js
style/consent.less

Phabricator Link: https://phabricator.wikimedia.org/T256202
Consent messages need to be aligned vertically
Use flexbox to align consent messages vertically

T256202: Use flexbox to align consent messages vertically

---

style/feedback.less

Phabricator Link: https://phabricator.wikimedia.org/T236317
Just some minor CSS adjustments regarding feedback component: 
* Have success/cancel confirmation messages be vertically and horizontally centered aligned
* Ensure all text is displayed in Hindi and other longer-character languages in Jio2
This PR is ready for reviewing/approving but let's hold off on merging until Sudhanshu confirms one final time on device within the next 24 hours.

T236317 feeback component css tweak

---

cypress/integration/settings-spec.js

Now that [these translations](https://github.com/wikimedia/wikipedia-kaios/commit/cf2f2af7f93edceeaa1fb9be5b7ae48edca983c4) are in, we can update tests and address pending TODO.

Update enJson to nlJson

---

package-lock.json
package.json
src/components/Search.js

Phabricator Link: https://phabricator.wikimedia.org/T262591
The search input allows an unlimited number of characters but the API allows only 255.
Limit search input to 255 characters to avoid useless and noisy error.

Limit length of search input according to search API restriction

---

package-lock.json
package.json

Phabricator Link: https://phabricator.wikimedia.org/T262596
I can't reproduce the error, and this is what I found and possibly to prevent the error

Upgrade banana-i18n version to 2.0.0

---

src/utils/languages.js
style/listview.less
style/menu.less
style/privacyterms.less
style/radiolistview.less
style/settings.less
style/toc.less

Phabricator Link: https://phabricator.wikimedia.org/T267289
Current search results highlighter is too light to be noticed
Update styling as outlined by design

T267289: Update highlighter styling

---

src/api/getLanglinks.js
src/hooks/useSearchLanguage.js
src/utils/languages.js

Phabricator Link: https://phabricator.wikimedia.org/T267290
During usability sessions, some users expressed that having Indian languages on top would help them within the article menu.
Shows the priority language list first, then the rest. (order based on FIFO)
**Jio**
| App Language (Before) | App Language (After) |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2560096/100077960-4299e300-2e43-11eb-938f-f8c352a37ad0.png) | ![image](https://user-images.githubusercontent.com/2560096/100078409-c94ec000-2e43-11eb-829c-b4f6e9a1aed6.png) |
| Article Cat Language (Before) | Article Cat Language (After) |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2560096/100078220-94db0400-2e43-11eb-8563-23490d101a99.png) | …

T267290 For Jio users show Indian languages on top inside the article menu

---

cypress/integration/special-cases.js
src/components/Gallery.js
style/gallery.less

https://phabricator.wikimedia.org/T269213
Removes image caption to allow for more viewing area.

T269213: Remove gallery caption

---

style/footer.less

Phabricator Link: https://phabricator.wikimedia.org/T269822
background too light
| ![d6d086f5-0fbf-414d-b42d-3a824c532b00-8080 apps codespaces githubusercontent com_](https://user-images.githubusercontent.com/2560096/101804832-4ea7c500-3b12-11eb-852c-bae5b9d23e63.png) |  ![d6d086f5-0fbf-414d-b42d-3a824c532b00-8080 apps codespaces githubusercontent com_ (1)](https://user-images.githubusercontent.com/2560096/101804828-4c456b00-3b12-11eb-95b7-77b5d6b09df3.png) |
| --- | --- |

T269822 Improve the visibility of suggested article section.

---

src/components/ArticleMenu.js
src/components/PopupContainer.js

Phabricator Link: https://phabricator.wikimedia.org/T267293
The article menu popup is partly shown behind the text size popup.
Introduce a way for popups to specify that they want to be the only popup visible.

Hide others

---

package-lock.json
package.json

bump cypress version

---

src/components/TextSize.js
src/utils/articleTextSize.js
style/textsize.less

The visual UI of the text size component doesn't feel right
calculate the portion to get the nearest value
merge to refactor branch

show the equal portion for each slider value

---

cypress/integration/settings-spec.js
src/components/Settings.js

Phabricator Link: https://phabricator.wikimedia.org/T270110
-
feedback first then about wikipedia
very quick one

T270110 reorder setting list

---

src/components/TextSize.js
src/utils/articleTextSize.js
style/textsize.less

Phabricator Link: https://phabricator.wikimedia.org/T271461
UI issue
1. press left/right to change text size, the circle doesn't look equally in the line
1. the line renders wrongly in right-to-left app language
fix it

T271461 Polish textsize slider and add RTL support in TextSize component

---

scripts/zip.sh
webpack.config.js

Sometimes you need to step through the code.
Add source-map to view the source in the browser debugger as written.

Add source-map for local debugging

---

cypress/integration/settings-spec.js
manifest.webapp

the build script will update manifest version using package.json, but we should also update it within the manifest file, so we get the correct version number during development.
update version in manifest

Update version in Manifest file

---

sim.html

- Turn off autocomplete for the experiment setting
- Some styling of control panel
- sim markup cleanup

Minor sim cleanup and config styling

---

src/hooks/useTracking.js

Phabricator Link: https://phabricator.wikimedia.org/T276475
filter out data from the all the development versions being tested by the team.
update new version of schema with new key `is_production`

T276475 add new key is_production in InukaPageView

---

sim.html

Toggling the experiment box doesn't change the application state.
Reload the iframe to make sure the app is up to date with the experiment config.

Reload sim after changing experiment config

---

sim.html

Phabricator Link: https://phabricator.wikimedia.org/T277257
The simulator is getting more popular but it may not work with all browsers config.
Fix what we know about (sendBeacon) and add a disclaimer and some help.
Sim Link: https://wikimedia.github.io/wikipedia-kaios/sim-beta/sim.html

Flag simulator as BETA

---

src/components/Article.js
src/components/Search.js
src/hooks/useTracking.js
src/utils/consent.js
src/utils/sendEvent.js
src/utils/sendFeedback.js

Phabricator Link: https://phabricator.wikimedia.org/T273219
The event object was missing some fields
Add `client_dt`, `webhost`, `wiki`, `schema`
Sim Link: https://wikimedia.github.io/wikipedia-kaios/<BRANCH NAME>/sim.html

Events: add missing fields

---

src/components/Feed.js
src/hooks/useExperimentConfig.js
style/feed.less

Related phabricators: https://phabricator.wikimedia.org/T271677, https://phabricator.wikimedia.org/T271904
A final follow up PR to update some minor styling. Note this PR will fail tests because of https://github.com/wikimedia/wikipedia-kaios/commit/bfb4d21efe20d0a70683eecf47c5e34f29a8b688, I will revert that before this is ready to merge. 
Sim Link: https://wikimedia.github.io/wikipedia-kaios/device-experiment-styling/sim.html

Experiment UI final touches

---

package-lock.json
package.json

Phabricator Link: https://phabricator.wikimedia.org/project/view/4301/
_Describe the statement of this pr_
_Describe the technical solution and attach the screenshot if needed_
Sim Link: https://wikimedia.github.io/wikipedia-kaios/cypress-bump-version/sim.html

cypress bump version

---

src/api/getArticleMediaInfo.js
src/api/getArticleMediaList.js
src/components/Gallery.js
src/hooks/useArticleMediaInfo.js
src/utils/mwApi.js

Phabricator Link: https://phabricator.wikimedia.org/T289273
image doesn't showed up in some articles
use the proper `imageinfo` api
Sim Link: https://wikimedia.github.io/wikipedia-kaios/T289273-image-not-loading/sim.html

T289273 fix image not loading

---

src/components/Search.js
src/hooks/useExperimentConfig.js

Phabricator Link: https://phabricator.wikimedia.org/T311142
Disable the Feature
return false but not removing the entire code yet

Disable the Experimental Group (not removing the entire code)

---

cypress/integration/references-popup.js

fix reference test spec
